-- MySQL Script generated by MySQL Workbench
-- Wed May 14 16:58:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema homedepot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homedepot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homedepot` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `homedepot` ;

-- -----------------------------------------------------
-- Table `homedepot`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`articulos` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`articulos` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `existencias` INT NOT NULL,
  `codigo_bar` CHAR(13) NOT NULL,
  `unidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_articulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `homedepot`.`cajas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`cajas` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`cajas` (
  `idCajas` INT NOT NULL AUTO_INCREMENT,
  `tipo_pago_aceptado` VARCHAR(45) NOT NULL,
  `saldocorte` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idCajas`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `homedepot`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`empleados` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`empleados` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `sueldo` DECIMAL(10,2) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `homedepot`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`clientes` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`clientes` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_1` VARCHAR(70) NOT NULL,
  `calle_ynum` VARCHAR(100) NOT NULL,
  `telefono` CHAR(10) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nombre_2` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `homedepot`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`ventas` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`ventas` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `id_Cliente` INT NULL DEFAULT NULL,
  `metodo_pago` VARCHAR(45) NOT NULL,
  `idEmpleado` INT NOT NULL,
  `promociones` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Ventas_Clientes_idx` (`id_Cliente` ASC) VISIBLE,
  INDEX `fk_Ventas_Empleados1_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Clientes`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `homedepot`.`clientes` (`id_Cliente`),
  CONSTRAINT `fk_Ventas_Empleados1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `homedepot`.`empleados` (`idEmpleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `homedepot`.`cambiosydevoluciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`cambiosydevoluciones` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`cambiosydevoluciones` (
  `idCambiosyDevoluciones` INT NOT NULL AUTO_INCREMENT,
  `razon_cambio` VARCHAR(1000) NULL DEFAULT NULL,
  `fecha_cambio` DATE NULL DEFAULT NULL,
  `idEmpleado` INT NOT NULL,
  `idVenta` INT NOT NULL,
  PRIMARY KEY (`idCambiosyDevoluciones`),
  INDEX `fk_Cambios y Devoluciones_Empleados1_idx` (`idEmpleado` ASC) VISIBLE,
  INDEX `fk_Cambios y Devoluciones_Ventas1_idx` (`idVenta` ASC) VISIBLE,
  CONSTRAINT `fk_Cambios y Devoluciones_Empleados1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `homedepot`.`empleados` (`idEmpleado`),
  CONSTRAINT `fk_Cambios y Devoluciones_Ventas1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `homedepot`.`ventas` (`idVenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `homedepot`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`proveedores` (
  `idProveedores` INT NOT NULL AUTO_INCREMENT,
  `Nombre_prov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `homedepot`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`compras` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`compras` (
  `idProveedores` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `costo_compra` DECIMAL(10,2) NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `cantidad_compra` INT NOT NULL,
  `Id_compras` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id_compras`),
  INDEX `fk_Proveedores_has_Articulos_Articulos1_idx` (`id_articulo` ASC) VISIBLE,
  INDEX `fk_Proveedores_has_Articulos_Proveedores1_idx` (`idProveedores` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedores_has_Articulos_Articulos1`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `homedepot`.`articulos` (`id_articulo`),
  CONSTRAINT `fk_Proveedores_has_Articulos_Proveedores1`
    FOREIGN KEY (`idProveedores`)
    REFERENCES `homedepot`.`proveedores` (`idProveedores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `homedepot`.`detalleventa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`detalleventa` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`detalleventa` (
  `idVenta` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idVenta`, `id_articulo`),
  INDEX `fk_Ventas_has_Articulos_Articulos1_idx` (`id_articulo` ASC) VISIBLE,
  INDEX `fk_Ventas_has_Articulos_Ventas1_idx` (`idVenta` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_has_Articulos_Articulos1`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `homedepot`.`articulos` (`id_articulo`),
  CONSTRAINT `fk_Ventas_has_Articulos_Ventas1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `homedepot`.`ventas` (`idVenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `homedepot`.`usocajas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homedepot`.`usocajas` ;

CREATE TABLE IF NOT EXISTS `homedepot`.`usocajas` (
  `idCajas` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idCajas`, `idEmpleado`, `fecha_inicio`),
  INDEX `fk_Cajas_has_Empleados_Empleados1_idx` (`idEmpleado` ASC) VISIBLE,
  INDEX `fk_Cajas_has_Empleados_Cajas1_idx` (`idCajas` ASC) VISIBLE,
  CONSTRAINT `fk_Cajas_has_Empleados_Cajas1`
    FOREIGN KEY (`idCajas`)
    REFERENCES `homedepot`.`cajas` (`idCajas`),
  CONSTRAINT `fk_Cajas_has_Empleados_Empleados1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `homedepot`.`empleados` (`idEmpleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
